project:
  type: website

website:
  title: "Alphorngruppe Rigi-Mythen"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Erstellt mit ❤️ und Quarto"
  navbar:
    search: false
    left:
      - text: Neuigkeiten
        href: news.qmd
  llms-txt: true
  announcement:
    icon: info-circle
    content: "Wettvortrag der Alphorngruppe Rigi-Mythen am Sa, 27. Juni 2026, um 15.30 Uhr auf dem Wettspielplatz beim Schulhaus St. Johann in Basel. Wir freuen uns auf euch!"
    type: success
    position: below-navbar
    dismissible: false

format:
  html:
    theme: [simplex, styles.scss]
    email-obfuscation: javascript

